README.md
www/Dockerfile
www/README.md
www/_app_/docusaurus.config.js
www/_app_/package-lock.json
www/_app_/package.json
www/_app_/sidebars.dev.js
www/_app_/sidebars.docs.js
www/docker-compose.yml

Right now there’s no way to preview the pages in the www directory. The only way to preview them is to pull the latest submodule master branch and run. We want to be able to run docausaurus in a docker container.
* Added Dockerfile
* Added docker-compose.yml
* Added relevant app configuration in _app_ directory

OSS-80: added docs preview scripts

---

www/_app_/docusaurus.config.js

Fix dev page preview, due to the default preset not having the dev parser.
* Use `@docusaurus/plugin-content-docs` plugin in `docusaurus.config.js`. 

NONE: fix dev pages preview

---

www/_app_/pages/docs/api.js
www/docker-compose.yml

Introduced some changes to www viewer to be able to view API docs.
* Updated docker-compose file
* Added api docs page (redoc standalone widget)

NONE: add API docs to www-viewer

---

core/api/swagger/swagger.yaml
core/internal/http/http_endpoints.go
core/internal/resource/resource_type.go
core/migrations/000009_init_identity.up.sql
core/migrations/000012_init_trait.down.sql
core/migrations/000012_init_trait.up.sql
core/pkg/trait/trait.go
core/pkg/trait/trait_http.go
core/pkg/trait/trait_service.go
core/pkg/trait/trait_util.go

Added a trait resource, which is essentially a single trait unit that will make up our trait catalog. Traits can be used when creating segments or custom flag targeting rules.  
* Added resource
* Added http handlers
* Added resource utils
* Updated swagger file

COM-22: added trait resource

---

.github/workflows/ci-flagbase-ui.yml

Added CI for UI that builds, tests & ensures linting
* Added `.github/workflows/ci-flagbase-ui.yml`

OSS-68: added CI via github actions for UI

---

core/internal/app/access/access_api.go
core/internal/app/environment/environment_api.go
core/internal/app/flag/flag_api.go
core/internal/app/healthcheck/healthcheck_api.go
core/internal/app/identity/identity_api.go
core/internal/app/project/project_api.go
core/internal/app/segment/segment_api.go
core/internal/app/segmentrule/segmentrule_api.go
core/internal/app/trait/trait_api.go
core/internal/app/variation/variation_api.go
core/internal/app/workspace/workspace_api.go

We want to distinguish between different worker modes (api, streamer). In order to make the worker-mode specific code easier to find, we'll use consistent terminology. 
* Rename *HTTPHandler -> *APIHandler

REFACTOR: http handler -> api handler

---

core/api/swagger/swagger.yaml
core/internal/app/segmentrule/segmentrule_api.go
core/internal/app/segmentrule/segmentrule_service.go
core/internal/app/segmentrule/segmentrule_util.go
core/migrations/000009_init_segment_rule.up.sql

We want to have different segment rules per environment (similar to targeting rules). This allows you to use segments to target users in different application environments (staging → employees, prod → customers etc). 
[https://flagbase.atlassian.net/browse/OSS-84](https://flagbase.atlassian.net/browse/OSS-84)
* Updated endpoints
* Updated services
* Updated service utils
* Updated swagger docs

OSS-84: update segment rules to be per-environment

---

core/docker-compose.yml

com.docker.backend now runs on port 5432, conflicting with postgres
* Update the exposed db port in `core/docker-compose.yml`

FIX: update exposed port for core db in docker-compose

---

core/api/swagger/swagger.yaml
core/internal/app/segment/segment_api.go
core/internal/app/segmentrule/segmentrule_api.go
core/internal/pkg/api/api_endpoints.go
core/internal/pkg/httputil/params.go
core/internal/pkg/resource/resource_route.go

Nest segment-rules in segment route as it makes sense semantically.
`/segment-rules/{workspaceKey}/{projectKey}/{segmentKey}/{envKey}/{ruleKey}`
`/segments/{workspaceKey}/{projectKey}/{segmentKey}/rules/{envKey}/{ruleKey}`
* Remove `segment-rules` from root endpoints in `api_endpoints.go`
* Apply `segment-rules` routes from segment handlers in `segment_api.go`
* Update swagger.yaml

OSS-87: nest segment-rules in segment route

---

core/api/swagger/swagger.yaml
core/internal/app/segment/segment_api.go
core/internal/app/targeting/targeting_api.go
core/internal/app/targetingrule/targetingrule_api.go
core/internal/pkg/api/api_endpoints.go

Nest targeting-rules in targeting route as it makes sense semantically.
* `/targeting-rules/{workspaceKey}/{projectKey}/{envKey}/{flagKey}`
* `/targeting-rules/{workspaceKey}/{projectKey}/{envKey}/{flagKey}/{ruleKey}`
* `/targeting/{workspaceKey}/{projectKey}/{envKey}/{flagKey}/rules`
* `/targeting/{workspaceKey}/{projectKey}/{envKey}/{flagKey}/rules/{ruleKey}`
* Remove targeting-rules from root endpoints in api_endpoints.go
* Apply targeting-rules routes from targeting handlers in targeting_api.go
* Update swagger.yaml

OSS-87: nest targeting-rules routes in targeting endpoint

---

core/api/swagger/swagger.yaml
core/internal/app/flag/flag_api.go
core/internal/app/variation/variation_api.go
core/internal/pkg/api/api_endpoints.go

Nest variations in flag route as it makes sense semantically.
* `/variations/{workspaceKey}/{projectKey}/{flagKey}`
* `/variations/{workspaceKey}/{projectKey}/{flagKey}/{variationKey}`
* `/flags/{workspaceKey}/{projectKey}/{flagKey}/variations`
* `/flags/{workspaceKey}/{projectKey}/{flagKey}/variations/{variationKey}`
* Remove variations from root endpoints in api_endpoints.go
* Apply variations routes from flag handlers in flag_api.go
* Update swagger.yaml

OSS-87: nest variation routes in flag endpoint

---

core/api/swagger/swagger.yaml
core/internal/app/environment/environment_api.go
core/internal/app/project/project_api.go
core/internal/app/variation/variation_api.go
core/internal/pkg/api/api_endpoints.go

Nest environments in project route as it makes sense semantically.
* `/environments/{workspaceKey}/{projectKey}/{envKey}`
* `/environments/{workspaceKey}/{projectKey}/{envKey}/access`
* `/environments/{workspaceKey}/{projectKey}`
* `/projects/{workspaceKey}/{projectKey}/environments/{envKey}`
* `/projects/{workspaceKey}/{projectKey}/environments/{envKey}/access`
* `/projects/{workspaceKey}/{projectKey}/environments`
* Remove environments from root endpoints in api_endpoints.go
* Apply environments routes from project handlers in project_api.go
* Update swagger.yaml

OSS-87: nest environment routes in project endpoint

---

core/docker-compose.yml
core/internal/pkg/constants/defaults.go
core/internal/pkg/polling/polling.go
core/internal/pkg/polling/polling_endpoints.go
core/internal/pkg/polling/polling_service.go
core/internal/pkg/polling/polling_util.go
core/internal/pkg/resource/resource_route.go

Connected evaluation service to polling worker. Also added `ETag` mechanism to cache polled responses.
* Updated `core/pkg/internal/polling` package
* Update `core/docker-compose.yml` to expose polling and streaming ports

OSS-86: added polling worker

---

core/internal/app/auth/auth_service.go
core/internal/app/environment/environment_service.go
core/internal/app/flag/flag_service.go
core/internal/app/identity/identity_service.go
core/internal/app/project/project_service.go
core/internal/app/sdkkey/sdkkey_repo.go
core/internal/app/sdkkey/sdkkey_service.go
core/internal/app/segment/segment_service.go
core/internal/app/segmentrule/segmentrule_service.go
core/internal/app/targeting/targeting_service.go
core/internal/app/targetingrule/targetingrule_service.go
core/internal/app/trait/trait_service.go
core/internal/app/variation/variation_service.go
core/internal/app/workspace/workspace_service.go
core/internal/pkg/httputil/token.go
core/internal/pkg/polling/polling.go
core/internal/pkg/polling/polling_endpoints.go
core/internal/pkg/polling/polling_service.go
core/internal/pkg/polling/polling_util.go
core/internal/pkg/server/server.go
core/internal/pkg/server/server_setup.go
core/migrations/000015_init_sdk_key.up.sql
core/pkg/evaluator/evaluator.go

SDK keys provide faster resource lookups rather than joining on workspace/project/environment keys.
```sh
curl --request POST \
--url http://127.0.0.1:9051/polling \
--header 'Content-Type: application/json' \
--header 'x-sdk-key: sdk-client_fbb5464-0a71-4fb0-9268-b426d6b710e5' \
--data '{
"identifier": "some-user-key",
"traits": {
"some-trait-key": "aaaa"
}
}'
```
* Updated polling service to use SDK key in header.

OSS-97: use sdk key in polling service

---

core/migrations/000003_init_project.up.sql
core/migrations/000004_init_environment.up.sql
core/migrations/000006_init_flag.up.sql
core/migrations/000007_init_variation.up.sql
core/migrations/000008_init_segment.up.sql
core/migrations/000009_init_segment_rule.up.sql
core/migrations/000010_init_identity.up.sql
core/migrations/000011_init_trait.up.sql
core/migrations/000012_init_targeting.up.sql
core/migrations/000013_init_targeting_rule.up.sql
core/migrations/000014_init_evaluation.up.sql
core/migrations/000015_init_sdk_key.up.sql

Add foreign key constraint to cascade on delete / update. So when top level resources are removed, child resources automatically get removed. 
* Update migrations

OSS-106: add fk constraint to cascade on delete / update 

---

ui/app/lib/entity-store/entity-context.tsx
ui/app/router/router.tsx
ui/tsconfig.json
ui/webpack/react.webpack.js

The webpack dev server and routing broke after dependabot updates. For some reason dependabot merged in breaking changes....
* Change 1
* ...

FIX: routing and webpack-dev-server after dependabot updates

---

core/cmd/manage/manage_access.go
core/cmd/worker/worker_api.go
core/cmd/worker/worker_setup.go
core/internal/pkg/cmdutil/global_flags.go
core/internal/pkg/constants/defaults.go
core/internal/pkg/osenv/osenv.go

Read from env variables when flags are not set.
* Added the following env variables: `FLAGBASE_CORE_PG_URL`, `FLAGBASE_CORE_REDIR_ADDR`, `FLAGBASE_CORE_REDIS_PASSWORD`, `FLAGBASE_CORE_REDIS_DB` 

Default to flags when env variables are not set

---

www/Dockerfile

Redoc doesn't like node 16.3 for some reason...
* Change 1
* ...

cjoy: fix docker version for docusaurus

---

core/internal/app/healthcheck/model/healthcheck_model.go
core/internal/app/healthcheck/service/healthcheck_service.go
core/internal/app/healthcheck/transport/healthcheck_api.go
sdk/js-client-sdk/examples/polling-app.stories.tsx

`/healthcheck` endpoint to return data about db and cache status
* Add HealthStatus model
* Update healthcheck service
* Update healthcheck endoints

cjoy: /healthcheck endpoint to return more info

---

core/internal/pkg/httpserver/httpserver.go

PATCH is not included in the CORS allowed methods list.... which explains why it's erroring out.
* Change 1
* ...

HOTFIX: add patch to cors whitelist

---

core/internal/app/project/service/project_service_util.go

Should use correct default environment key for staging sdk keys. 
* Change 1
* ...

OSS-124: use correct default environment key from staging sdk
