- www/blog/2020-11-05-gensis.md
- www/dev/README.md
- www/docs/README.md
Just updated the intro blog post
* Rename intro blog post -> genesis
* Update blog post contents
> NONE: update intro blog post

- .github/workflows/ci-flagbase-core.yml
- README.md
- core/api/swagger/swagger.yaml
- core/internal/http/http_endpoints.go
- core/pkg/environment/environment.go
- core/pkg/environment/environment_http.go
- core/pkg/environment/environment_service.go
- core/pkg/environment/environment_util.go
- core/pkg/project/project_service.go
- core/pkg/project/project_util.go
- core/pkg/workspace/workspace_service.go
- core/pkg/workspace/workspace_util.go
Projects contain different environments, allowing us to have multiple flagset states.
* Added env pkg (http handers, service, utils etc)
* Updated swagger definitions
> OSS-51: added environment pkg, updated swagger defs

- core/api/swagger/swagger.yaml
- core/internal/http/http_endpoints.go
- core/pkg/flag/flag.go
- core/pkg/flag/flag_http.go
- core/pkg/flag/flag_service.go
- core/pkg/flag/flag_util.go
- core/pkg/project/project_service.go
Added the flag resource. A flag (aka feature flag) consists of a set of variations and represents the state of a feature in a project.
* Updated swagger spec
* Added model
* Added service
* Added utils
* Added HTTP handlers
> Oss 52 flags

- core/api/swagger/swagger.yaml
- core/internal/http/http_endpoints.go
- core/pkg/identity/identity.go
- core/pkg/identity/identity_http.go
- core/pkg/identity/identity_service.go
- core/pkg/identity/identity_util.go
Identity represents a flag consumer (i.e. an entity which requests for an evaluated flagset). 
* Added service
* Added utils
* Added model
* Added http handlers
* Update swagger file
> OSS-22: added identity resource

- core/api/swagger/swagger.yaml
- core/internal/http/http_endpoints.go
- core/migrations/000008_init_segment.up.sql
- core/pkg/segment/segment.go
- core/pkg/segment/segment_http.go
- core/pkg/segment/segment_service.go
- core/pkg/segment/segment_util.go
Segment represents a group of identities with similar characteristics.
* Added service / utils
* Added types
* Added http handlers
* Added segment rule types
> OSS-24: added segment resource

- core/api/swagger/swagger.yaml
- core/internal/http/http_endpoints.go
- core/internal/resource/resource_type.go
- core/pkg/segmentrule/segmentrule.go
- core/pkg/segmentrule/segmentrule_http.go
- core/pkg/segmentrule/segmentrule_service.go
- core/pkg/segmentrule/segmentrule_util.go
A segment rule represents a condition used to filter identities for a particular segment
* Added service / utils
* Added types
* Updated swagger spec
> OSS-24: segment rules

- ui/.eslintignore
- ui/.eslintrc.json
- ui/.prettierrc
- ui/.storybook/main.js
- ui/.storybook/preview.js
- ui/README.md
- ui/app/containers/Entry/Entry.styles.tsx
- ui/app/containers/Entry/Entry.tsx
- ui/app/containers/Entry/index.tsx
- ui/babel.config.js
- ui/components/Button/Button.spec.tsx
- ui/components/Button/Button.stories.tsx
- ui/components/Button/Button.tsx
- ui/components/Button/index.tsx
- ui/components/Greetings/Greetings.spec.tsx
- ui/components/Greetings/Greetings.styles.ts
- ui/components/Greetings/Greetings.tsx
- ui/components/Greetings/index.tsx
- ui/electron/index.ts
- ui/jest.config.js
- ui/package-lock.json
- ui/package.json
- ui/tests/setupTests.ts
- ui/tsconfig.json
- ui/webpack/electron.webpack.js
- ui/webpack/react.webpack.js
Initialize UI. 
RFC: https://flagbase.atlassian.net/wiki/spaces/OSS/pages/692813825/RFC+-+UI+Architecture
* Added electron config
* Added react
* Added antd
* Added storybook
* Added example storybook components
* Added webpack configuration files
> OSS 37: init UI

- core/cmd/manage/manage_access.go
- core/cmd/service/service.go
- core/cmd/service/service_api.go
- core/cmd/service/service_polling.go
- core/cmd/service/service_streamer.go
- core/internal/app/healthcheck/healthcheck_service.go
- core/internal/pkg/api/api_endpoints.go
- core/internal/pkg/api/api_server.go
- core/internal/pkg/constants/defaults.go
- core/internal/pkg/httpmetrics/httpmetrics.go
- core/internal/pkg/httpserver/httpserver.go
- core/internal/pkg/polling/polling_endpoints.go
- core/internal/pkg/polling/polling_server.go
- core/pkg/logger/logger.go
Add new polling worker (run on another thread in default mode).
[https://flagbase.atlassian.net/browse/OSS-85](https://flagbase.atlassian.net/browse/OSS-85)
* Add common httpserver, httpmetrics package
* Update api package to use httpservice & httpmetrics
* Add polling package
* FIX: logger should invoke new instance of *zerolog.Event
> Oss 85/polling mode

- core/README.md
- core/internal/pkg/polling/polling_server.go
- www/dev/core/1_getting-started.md
- www/dev/core/2_architecture.md
Added content to this page: https://flagbase.com/dev/core/architecture
* Update `www/dev/core/2_architecture.md`
> OSS-63: added core architecture page

- core/internal/app/targeting/targeting_repo.go
- core/internal/app/targetingrule/targetingrule.go
- core/internal/app/targetingrule/targetingrule_api.go
- core/internal/app/targetingrule/targetingrule_repo.go
- core/internal/app/targetingrule/targetingrule_service.go
- core/internal/pkg/api/api_endpoints.go
- core/internal/pkg/resource/resource_route.go
- core/internal/pkg/resource/resource_type.go
This PR introduces the targeting_rule module. Basically extending [PR #60](https://github.com/flagbase/flagbase/pull/60) so users can add rules to their base targeting configuration for a flag in a particular project environment.
```sh
curl --request GET \
--url http://127.0.0.1:5051/targeting-rules/{workspaceKey}/{projectKey}/{envKey}/{flagKey} \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9....'
```
```sh
curl --request POST \
--url http://127.0.0.1:5051/targeting-rules/{workspaceKey}/{projectKey}/{envKey}/{flagKey} \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...' \
--header 'Content-Type: application/json' \
--data '{
"key": "test-targeting-rule",
"type": "trait",
"name": "Example Name",
"description": "This should be a description.", …
```
> OSS-23: added targeting_rule module

- core/api/swagger/swagger.yaml
Remove auditlog from swagger spec
* Change 1
* ...
> ADHOC: remove auditlog from swagger

- core/api/swagger/swagger.yaml
- core/go.mod
- core/internal/app/evaluation/evaluation.go
- core/internal/app/evaluation/evaluation_api.go
- core/internal/app/evaluation/evaluation_service.go
- core/internal/app/segmentrule/segmentrule.go
- core/internal/app/targeting/targeting.go
- core/internal/app/targeting/targeting_repo.go
- core/internal/app/targetingrule/targetingrule.go
- core/internal/app/targetingrule/targetingrule_repo.go
- core/internal/pkg/api/api_endpoints.go
- core/internal/pkg/resource/resource_route.go
- core/pkg/evaluator/bucket.go
- core/pkg/evaluator/engine.go
- core/pkg/evaluator/evaluator.go
- core/pkg/evaluator/matcher.go
- core/pkg/evaluator/reason.go
- core/pkg/flagset/flagset.go
- core/pkg/flagset/operand.go
- core/pkg/flagset/rule.go
- core/pkg/flagset/variations.go
- core/pkg/hashutil/hashutil.go
This PR introduces the evaluation endpoints and evaluator package. The evaluator package is reusable, allowing us to re-use it in our go-server-sdk in the future. 
Read more about the [evaluation engine here](https://flagbase.atlassian.net/wiki/spaces/OSS/pages/556367945/RFC+-+Targeting#Evaluation-Engine).
* Added evaluator package with evaluation engine
* Added evaluation endpoint
* Updated swagger
> OSS-86: evaluation

- core/api/swagger/swagger.yaml
- core/internal/app/sdkkey/sdkkey.go
- core/internal/app/sdkkey/sdkkey_api.go
- core/internal/app/sdkkey/sdkkey_repo.go
- core/internal/app/sdkkey/sdkkey_service.go
- core/internal/pkg/resource/resource_key.go
- core/internal/pkg/resource/resource_route.go
- core/internal/pkg/resource/resource_type.go
- core/migrations/000015_init_sdk_key.down.sql
- core/migrations/000015_init_sdk_key.up.sql
Added SDK key resource to provide faster environment lookups. SDK keys can be easily rotated and provide different keys for server & client side SDKs.  
* Added service
* Added data repository
* Added model
* Added api handlers
* Update swagger
> OSS-96: added sdk key resource

- README.md
- core/api/swagger/swagger.yaml
- www/_app_/css/redoc.override.css
- www/_app_/pages/docs/api.js
- www/docker-compose.yml
Updated API docs to include json:api models / examples. 
* Update `core/api/swagger/swagger.yaml`
> ADHOC: improve api docs

- core/api/swagger/swagger.yaml
Clean up swagger docs. 
* Use re-usable components and responses
* Add request and response examples
> OSS-89: incremental progress on swagger cleanup

- www_v2/Dockerfile
- www_v2/README.md
- www_v2/_app_/docusaurus.config.js
- www_v2/_app_/src/css/custom.css
- www_v2/docker-compose.yml
> Com 28/www v2 api docs

- .github/dependabot.yml
Update dependabot schedule interval to only once per day
> ADHOC: update dependabot scan freq

- .github/dependabot.yml
Update dependabot schedule to only update weekly
> dependabot: only update packages weekly

- core/Dockerfile
Provide some background to what this change is and why it's important.
* Change 1
* ...
> feat: use specific alpine version to prevent go air not found issue

- .github/workflows/ci-dependabot.yml
- .github/workflows/ci-flagbase-core.yml
- core/.golangci.yml
- core/Dockerfile
- core/README.md
- core/cmd/manage/manage_access.go
- core/cmd/worker/worker_cmd.go
- core/docker-compose.yml
- core/internal/app/environment/service/environment_service_util.go
- core/internal/app/project/service/project_service_util.go
- core/internal/pkg/cmdutil/global_flags.go
- core/internal/pkg/constants/defaults.go
- core/internal/pkg/osenv/osenv.go
- core/pkg/evaluator/bucket.go
- core/pkg/evaluator/matcher.go
Developer productivity improvements.
* Introduce revise
* Environment variables (no longer dependent on flags)
* Dockerfile no longer relies on air
> * introduce revise (replaces golint), fix linting issues

- .github/workflows/release-flagbase-core-dockerhub.yml
- core/.golangci.yml
Publish core image to dockerhub.
* Change 1
* ...
> cjoy: publish core image to dockerhub

- .github/workflows/release-flagbase-core-dockerhub.yml
- core/.golangci.yml
Fix CI to build and push to docker 
* Change 1
* ...
> cjoy: fix build and publish to docker

- core/Dockerfile
Add entrypoint in dockerfile
* Change 1
* ...
> cjoy: add entrypoint in Dockerfile

- core/docker-compose.yml
- core/go.mod
- core/go.sum
- core/internal/pkg/policy/policy_setup.go
Use github.com/pckhoi/casbin-pgx-adapter as it supports dsn connections 
* Change 1
* ...
> cjoy: fix pg adaptor

- core/api/swagger/swagger.yaml
- sdk/js-client-sdk/src/context/config.ts
Change service URLs from flagbase.io -> flagbase.com
* Change 1
* ...
> cjoy: change service urls

- README.md
- www/content/blog/2021-03-20-take-control-of-your-feature-management-platform.md
- www/content/blog/2023-01-19-best-practices-for-feature-releases.md
- www/content/docs/intro/overview.md
Provide some background to what this change is and why it's important.
* Change 1
* ...
> cjoy: adhoc fix up content

- www/content/blog/2023-03-05-intro-to-advance-deployments-using-feature-flags.md
Add more images to intro to advanced deployments blog post.
* Add more images
> cjoy: add more images

- core/Dockerfile
Provide some background to what this change is and why it's important.
* Change 1
* ...
> OSS-121: update go dockerfile

- .github/workflows/ci-flagbase-ui.yml
- .github/workflows/ci-flagbase-www.yml
- .github/workflows/ci-health-codeball.yml
- .github/workflows/release-flagbase-core.yml
- .gitignore
- ui/.firebaserc
- ui/.gitignore
- ui/firebase.json
- ui/jest.config.js
- www/.firebaserc
- www/README.md
- www/docker-compose.yml
- www/firebase.json
Provide some background to what this change is and why it's important.
* Change 1
* ...
> Cjoy/deploy UI app

- core/api/swagger/swagger.yaml
Remove docs on project and workspace access paths
* Change 1
* ...
> Modified core/api/swagger/swagger.yaml

- .gitignore
- sdk/README.md
- sdk/js-client-sdk/README.md
- sdk/js-client-sdk/package.json
- sdk/react-client-sdk/README.md
- sdk/react-client-sdk/package.json
- sdk/react-client-sdk/pnpm-lock.yaml
- sdk/react-client-sdk/src/context.ts
- sdk/react-client-sdk/src/index.ts
- sdk/react-client-sdk/src/provider.tsx
- sdk/react-client-sdk/src/useFeatureFlag.ts
- sdk/react-client-sdk/src/useFlagbaseClient.ts
- sdk/react-client-sdk/tsconfig.json
- www/content/blog/2023-03-15-new-javascript-react-client-sdks.md
- www/content/docs/core/setup.md
- www/content/docs/guides/project.md
- www/content/docs/guides/segment.md
- www/content/docs/guides/targeting.md
- www/content/docs/sdk/javascript.md
- www/content/docs/sdk/overview.md
- www/content/docs/sdk/react.md
Add react SDK & improve docos
* Add `sdk/react-client-sdk`
* Improve SDK docs
> cjoy: add new react SDK and improve docs

- core/internal/app/evaluation/repository/evaluation_repo.go
- www/content/dev/core/data-models.md
Evaluation response isn't returning the correct response. Tests need to be added
* Change 1
* ...
> fix: evaluation rules should return correct values

- ui/components/page-layout/page-layout.tsx
- ui/webpack/react.webpack.js
Change app title 
* Change 1
* ...
> feature: change title on UI app

- ui/app/pages/flags/api.tsx
- ui/app/pages/flags/flags.edit.tsx
- ui/app/pages/flags/flags.modal.tsx
- ui/app/pages/flags/flags.tsx
- ui/app/pages/instances/instances.settings.tsx
- ui/app/pages/projects/api.tsx
- ui/app/pages/projects/edit-environment.tsx
- ui/app/pages/projects/environments.tsx
- ui/app/pages/projects/projects.edit.tsx
- ui/app/pages/projects/projects.tsx
- ui/app/pages/sdks/api.ts
- ui/app/pages/sdks/sdks.modal.tsx
- ui/app/pages/sdks/sdks.tsx
- ui/app/pages/workspaces/api.tsx
- ui/app/pages/workspaces/workspaces.edit.tsx
- ui/app/pages/workspaces/workspaces.main.tsx
- ui/app/router/loaders.tsx
- ui/app/router/router.tsx
- ui/components/input/tag-input.tsx
- ui/components/input/toggle.tsx
- ui/components/page-layout/page-layout.tsx
- ui/components/tag/index.tsx
Provide some background to what this change is and why it's important. it's 3 am i sleep
* Change 1
* ...
> Update/Delete for workspaces, projects, environments, flags, SDKs

- ui/app/pages/targeting/targeting.tsx
- ui/app/pages/workspaces/workspace.constants.tsx
- www/content/dev/intro/overview.md
- www/content/dev/intro/workflow.md
- www/content/dev/sdk/javascript.md
- www/content/dev/sdk/react.md
Improve targeting UI and add some developer docs
* Change 1
* ...
> adhoc: improve docs and UI

- ui/components/page-layout/footer.tsx
- ui/components/page-layout/page-layout.tsx
Small UI improvements after receiving user feedback.
**Before**
**After**
* Change 1
* ...
> fix: small ui improvements

- ui/app/lib/axios.ts
- ui/app/pages/flags/api.tsx
- ui/app/pages/flags/flags.tsx
- ui/app/pages/instances/instances.modal.tsx
- ui/app/pages/sdks/sdk.settings.tsx
- ui/app/pages/targeting/targeting-rule.tsx
- ui/app/pages/targeting/targeting.tsx
- ui/app/pages/workspaces/workspaces.edit.tsx
- ui/components/button/button.tsx
- ui/components/loading-text/index.tsx
- ui/components/loading-text/loading-text.tsx
- ui/components/rollout-slider/rollout-slider.tsx
Fix loading state buttons...
* Fix loading state buttons
* Fix targeting view on safari
> fix: add is loading state

- sdk/react-client-sdk/.storybook/main.ts
- sdk/react-client-sdk/.storybook/preview-head.html
- sdk/react-client-sdk/.storybook/preview.ts
- sdk/react-client-sdk/examples/demo-app-navigation/App.stories.tsx
- sdk/react-client-sdk/examples/demo-app-navigation/App.tsx
- sdk/react-client-sdk/examples/demo-app-navigation/Navigation.tsx
- sdk/react-client-sdk/package.json
- sdk/react-client-sdk/pnpm-lock.yaml
- sdk/react-client-sdk/src/context.ts
- sdk/react-client-sdk/src/index.ts
- sdk/react-client-sdk/vite.config.ts
Add demo application in react client SDK, using storybooks
* Change 1
* ...
> React sdk improvements

- core/internal/app/environment/service/environment_service_util.go
- core/internal/app/flag/service/flag_service_util.go
- core/internal/app/targeting/repository/targeting_repo_util.go
- core/internal/app/targetingrule/repository/targetingrule_repo_util.go
- core/internal/app/variation/service/variation_service.go
- core/internal/app/variation/service/variation_service_util.go
- core/pkg/model/constants.go
There was an issue when creating a new variation for a flag. We didn't update the existing fallthrough and targeting rules for the given flag, across all environments.
And another issue when creating a new environnment. We didn't add all the variations to the fallthrough.
* Change 1
* ...
> Fix: address issue around creating new environments and variations

- package.json
- pnpm-lock.yaml
- sdk/js-client-sdk/package.json
- sdk/react-client-sdk/README.md
- sdk/react-client-sdk/package.json
Our react-client-sdk was broken due to mismatch react versions
> Update package lock files

- .github/workflows/ci-flagbase-client.yml
- .github/workflows/release-flagbase-client.yml
- client/.firebaserc
- client/firebase.json
We were targeting the wrong firebase hosting app, resulting in failed preview deploys
> Fix flagbase-client pipeline
